import type { Kata } from './types.js';

export const catalog: readonly Kata[] = [
  {
    id: 'symbol-registry',
    title: 'Symbol Metadata Registry',
    difficulty: 'beginner',
    topics: ['symbols', 'metadata'],
    summary: 'Use Symbol.for to create hidden feature toggles and store metadata safely.',
    entry: './src/katas/beginner/symbol-registry.ts',
    estimatedTime: '20-25 min',
    objectives: [
      'Derive deterministic symbol keys from namespace + feature names',
      'Attach metadata via non-enumerable symbol properties',
      'List only symbol keys belonging to the expected namespace',
    ],
    tips: [
      'Symbol.for stores keys globally; use namespace prefixes to avoid collisions',
      'Object.getOwnPropertySymbols returns all symbol keys including well-known ones',
    ],
  },
  {
    id: 'typedarray-pixel-buffer',
    title: 'TypedArray Pixel Buffer',
    difficulty: 'beginner',
    topics: ['typedarrays', 'arraybuffer'],
    summary: 'Allocate a framebuffer with Uint8ClampedArray and extract channels via TypedArrays.',
    entry: './src/katas/beginner/typedarray-pixel-buffer.ts',
    estimatedTime: '25-30 min',
    objectives: [
      'Share a single ArrayBuffer between multiple views',
      'Draw rows efficiently by reusing typed slices',
      'Normalize a color channel into Float32Array data',
    ],
    tips: ['Each pixel needs 4 bytes (RGBA)', 'Use subarray to avoid copying data'],
  },
  {
    id: 'buffer-packet-builder',
    title: 'Binary Packet Builder',
    difficulty: 'beginner',
    topics: ['buffers', 'binary-protocols'],
    summary: 'Implement a 4-byte header protocol using Buffers without concat overhead.',
    entry: './src/katas/beginner/buffer-packet-builder.ts',
    estimatedTime: '30-45 min',
    objectives: [
      'Allocate Buffers deterministically and write integers with the correct endianness',
      'Slice header/payload chunks without copying data unnecessarily',
      'Verify packet integrity via XOR checksum',
    ],
    tips: [
      'Prefer Buffer.alloc for predictable zeroed memory',
      'Avoid Buffer.concat in tight loops; reuse slices where possible',
    ],
  },
  {
    id: 'typed-event-bus',
    title: 'Typed Event Bus',
    difficulty: 'beginner',
    topics: ['events', 'generics'],
    summary: 'Wrap EventEmitter with compile-time safety and wildcard listeners.',
    entry: './src/katas/beginner/event-bus.ts',
    estimatedTime: '25-35 min',
    objectives: [
      'Use overloaded signatures to preserve listener types',
      'Implement wildcard listeners without breaking removeListener',
      'Propagate EventEmitter captureRejections to the caller',
    ],
    tips: [
      'Track listener references so off() removes the exact function',
      'Forward wildcard emits manually',
    ],
  },
  {
    id: 'async-log-stream',
    title: 'Async Log Streamer',
    difficulty: 'intermediate',
    topics: ['async-iterators', 'streams'],
    summary: 'Expose telemetry as async iterables with lazy filtering and aggregation.',
    entry: './src/katas/intermediate/async-log-stream.ts',
    estimatedTime: '35-45 min',
    objectives: [
      'Implement an async generator that cleans up file handles on exit',
      'Compose async iterables to filter events lazily',
      'Process rolling latency stats without materializing the dataset',
    ],
    tips: [
      'Use for await...of to consume upstream iterables',
      'Remember to close readline interfaces in finally',
    ],
  },
  {
    id: 'dns-cache',
    title: 'DNS Cache Resolver',
    difficulty: 'intermediate',
    topics: ['dns', 'caching'],
    summary: 'Wrap dns.promises APIs with TTL-aware caching and cancellation.',
    entry: './src/katas/intermediate/dns-cache.ts',
    estimatedTime: '30-40 min',
    objectives: [
      'Normalize hostnames and record types for cache keys',
      'Respect AbortSignal and reject with DOMException AbortError',
      'Sweep expired entries without blocking the event loop',
    ],
    tips: [
      'Store expiresAt timestamps and compare with Date.now()',
      'Deduplicate concurrent lookups via a pending map',
    ],
  },
  {
    id: 'https-health-check',
    title: 'HTTPS Health Check',
    difficulty: 'advanced',
    topics: ['https', 'streams', 'abort-controller'],
    summary: 'Drive raw https.request with per-target timeouts and bounded concurrency.',
    entry: './src/katas/advanced/https-health-check.ts',
    estimatedTime: '45-60 min',
    objectives: [
      'Wrap https.request in a Promise that resolves only after the response stream ends',
      'Handle AbortSignal and manual timeouts to cancel sockets',
      'Build a worker-pool style probeAll that reports progress',
    ],
    tips: [
      "Use once(response, 'end') to await completion",
      'Remember to cleanup listeners on early abort',
    ],
  },
  {
    id: 'event-loop-lab',
    title: 'Event Loop Lab',
    difficulty: 'advanced',
    topics: ['event-loop', 'timers', 'microtasks'],
    summary: 'Record the exact order of nextTick/microtask/immediate/timer execution.',
    entry: './src/katas/advanced/event-loop-lab.ts',
    estimatedTime: '30-40 min',
    objectives: [
      'Schedule handlers onto the correct queue',
      'Await async handlers before recording their completion',
      'Compare relative ordering between phases using timestamps',
    ],
    tips: [
      'queueMicrotask runs before next macrotask',
      'setImmediate fires before timers if scheduled within I/O callbacks',
    ],
  },
  {
    id: 'memory-pool',
    title: 'Buffer Pool + Finalizer',
    difficulty: 'advanced',
    topics: ['memory-management', 'finalization'],
    summary: 'Implement a slab allocator that can auto-release slices via FinalizationRegistry.',
    entry: './src/katas/advanced/memory-pool.ts',
    estimatedTime: '50-70 min',
    objectives: [
      'Manage a linked-list or array of free slots on top of a single Buffer',
      'Split and merge slots to minimize fragmentation',
      'Optionally tie leases to FinalizationRegistry to detect leaks',
    ],
    tips: [
      'Keep slot metadata small to avoid overhead',
      'Finalizers should be optional and resilient to GC delays',
    ],
  },
  {
    id: 'net-tcp-chat',
    title: 'TCP Chat Harness',
    difficulty: 'intermediate',
    topics: ['net', 'tcp', 'sockets'],
    summary: 'Create a TCP chat server that parses line commands and broadcasts messages.',
    entry: './src/katas/intermediate/net-tcp-chat.ts',
    estimatedTime: '35-45 min',
    objectives: [
      'Manage Socket lifecycles and idle timeouts',
      'Broadcast messages with backpressure awareness',
      'Clean up listeners and enforce graceful shutdown',
    ],
    tips: [
      'Remember to pause/resume sockets when buffering data',
      'Use once(socket, "close") helpers to await shutdown',
    ],
  },
  {
    id: 'fs-atomic-journal',
    title: 'Atomic Journal Writer',
    difficulty: 'intermediate',
    topics: ['fs', 'atomic-write'],
    summary: 'Append JSON entries via temp files + renames and maintain an index of offsets.',
    entry: './src/katas/intermediate/fs-atomic-journal.ts',
    estimatedTime: '30-40 min',
    objectives: [
      'Use fs.promises.open/FileHandle to append safely',
      'Implement atomic rename workflow to protect against crashes',
      'Stream log entries lazily using readline',
    ],
    tips: ['fsync temp files before renaming', 'Keep index metadata small and append-only'],
  },
  {
    id: 'crypto-sealed-box',
    title: 'Crypto Sealed Box',
    difficulty: 'intermediate',
    topics: ['crypto', 'signing', 'encryption'],
    summary: 'Generate Ed25519 key pairs, sign payloads, and encrypt blobs with AES-GCM.',
    entry: './src/katas/intermediate/crypto-sealed-box.ts',
    estimatedTime: '40-50 min',
    objectives: [
      'Use generateKeyPairSync to mint Ed25519 identities',
      'Sign and verify payloads using Buffer inputs',
      'Encrypt data with AES-256-GCM and produce sealed tokens',
    ],
    tips: ['Ed25519 ignores hash algorithm strings; pass null', 'Keep IVs unique per encryption'],
  },
  {
    id: 'stream-metrics-transform',
    title: 'Stream Metrics Transform',
    difficulty: 'intermediate',
    topics: ['streams', 'transform'],
    summary: 'Turn NDJSON into aggregated metrics using Transform streams and pipeline.',
    entry: './src/katas/intermediate/stream-metrics-transform.ts',
    estimatedTime: '35-45 min',
    objectives: [
      'Implement Transform streams in objectMode safely',
      'Buffer partial lines between chunks',
      'Respect backpressure by waiting for callback invocations',
    ],
    tips: ['Do not call callback twice per chunk', 'Flush buffered data on _flush'],
  },
  {
    id: 'url-sanitizer',
    title: 'URL Sanitizer',
    difficulty: 'intermediate',
    topics: ['url', 'routing'],
    summary: 'Normalize URLs, strip unwanted params, and match routes with URLPattern.',
    entry: './src/katas/intermediate/url-sanitizer.ts',
    estimatedTime: '20-30 min',
    objectives: [
      'Enforce HTTPS using the WHATWG URL API',
      'Manipulate search params predictably',
      'Use URLPattern.exec to capture dynamic segments',
    ],
    tips: [
      'URL objects are mutable; clone when necessary',
      'Remove default ports for canonical comparisons',
    ],
  },
  {
    id: 'udp-heartbeat-monitor',
    title: 'UDP Heartbeat Monitor',
    difficulty: 'advanced',
    topics: ['udp', 'dgram'],
    summary: 'Send and receive heartbeat packets over UDP with timeouts and retries.',
    entry: './src/katas/advanced/udp-heartbeat-monitor.ts',
    estimatedTime: '45-55 min',
    objectives: [
      'Encode timestamps and IDs into buffers manually',
      'Track pending responses per peer and enforce timeouts',
      'Shut down sockets cleanly when monitoring stops',
    ],
    tips: [
      'Use socket.unref() for background monitors',
      'Remember UDP messages might be lost or reordered',
    ],
  },
  {
    id: 'timer-wheel',
    title: 'Timer Wheel Scheduler',
    difficulty: 'advanced',
    topics: ['timers', 'scheduler'],
    summary: 'Coalesce timer callbacks into buckets for efficient scheduling.',
    entry: './src/katas/advanced/timer-wheel.ts',
    estimatedTime: '40-50 min',
    objectives: [
      'Implement a circular buffer of scheduled tasks',
      'Advance the wheel and execute due callbacks in order',
      'Support cancellation without leaking entries',
    ],
    tips: ['Use monotonic clocks when possible', 'Keep buckets as arrays for O(1) inserts'],
  },
  {
    id: 'worker-pool',
    title: 'Worker Thread Pool',
    difficulty: 'advanced',
    topics: ['worker-threads', 'parallelism'],
    summary: 'Dispatch CPU-bound work to a pool of Worker threads with graceful teardown.',
    entry: './src/katas/advanced/worker-pool.ts',
    estimatedTime: '60-70 min',
    objectives: [
      'Spawn workers with resource limits and message handlers',
      'Track pending tasks and resolve promises upon responses',
      'Terminate workers while rejecting outstanding work',
    ],
    tips: [
      'Keep a task id counter to correlate responses',
      'Listen for worker "error" and "exit" events',
    ],
  },
  {
    id: 'web-streams-adapter',
    title: 'Web Streams Adapter',
    difficulty: 'advanced',
    topics: ['web-streams', 'fetch'],
    summary: 'Bridge Node streams with Web Streams and tee fetch responses to multiple sinks.',
    entry: './src/katas/advanced/web-streams-adapter.ts',
    estimatedTime: '35-45 min',
    objectives: [
      'Wrap Node Readable into Web ReadableStream',
      'Adapt Web WritableStream back to Node Writable',
      'Use body.tee() to branch fetch responses',
    ],
    tips: [
      'Web Streams APIs live under stream/web module in Node 24',
      'Remember to close writers on completion or error',
    ],
  },
];

export type { Kata } from './types.js';
